(SERVER-3157) Add Snyk GH Action
puppetlabs/puppetserver pull request #2607
Opened 2022-01-27 19:54 UTC by Magisus

2022-01-27 20:03 UTC, Magisus commented
This doesn't seem to be working right yet.

2022-01-28 20:13 UTC, Magisus commented
For reasons that are entirely unclear to me, using the `pull_request_target` trigger does not appear to work. `pull_request` does.

2022-01-28 23:18 UTC, Magisus commented
Update: apparently you have to merge actions using the `pull_request_target` trigger before they will run. So I'm going to put this to `pull_request` for now so we can see it go, then flip to `pull_request_target` right before we merge.

2022-02-01 01:27 UTC, rileynewton requested changes
I found out from Jeremy that there's a specific puppet-foss token (there's a token for every org now I realize 🤦 ), you'll likely want to switch to that.

2022-02-01 01:40 UTC, Magisus commented
I asked him about that several times and he told me there was only one for anything that goes into PE...

2022-02-01 17:13 UTC, mwaggett commented on .travis.yml
> -        - lein nvd check
Should we also remove the plugin from project.clj and remove the suppression file?

2022-02-01 17:42 UTC, mwaggett approved these changes

2022-02-01 17:53 UTC, Magisus commented
Flipping this to `pull_request_target` now that Snyk has passed

2022-02-01 18:38 UTC, mwaggett approved these changes

2022-02-01 18:38 UTC, merged