(SERVER-3390): Fix smoke acceptance test suite for puppetserver in 7.x stream
puppetlabs/puppetserver pull request #2883
Opened 2024-09-26 15:00 UTC by span786

[Jenkins Pipeline for Smoke Acceptance test suite](https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppetserver_integration-system_no-conditional_smoke-7.x/) is failing with following errors:

Error Snippet from [this]([url](https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppetserver_integration-system_no-conditional_smoke-7.x/229/LAYOUT=ubuntu2204-64ma-64a,LDAP_TYPE=default,label=k8s-beaker/consoleFull)) pipeline

```
afraid-outpost.vmpooler-prod.puppet.net (afraid-outpost.vmpooler-prod.puppet.net) 20:25:25$ /opt/puppetlabs/puppet/bin/gem install r10k
13:25:25     ERROR:  While executing gem ... (NoMethodError)
13:25:50         undefined method `start_with' for "RDoc::Markup::Document":String
13:25:50     Did you mean?  start_with?
13:25:50     The `minitar` executable is no longer bundled with `minitar`. If you are
13:25:50     expecting this executable, make sure you also install `minitar-cli`.
13:25:50     Successfully installed minitar-0.12.1
13:25:50     Successfully installed jwt-2.9.1
13:25:50     Successfully installed erubi-1.13.0
13:25:50     Successfully installed gettext-3.4.9
13:25:50     Successfully installed fast_gettext-2.4.0
13:25:50     Successfully installed gettext-setup-1.1.0
13:25:50     Successfully installed faraday-follow_redirects-0.3.0
13:25:50     Successfully installed puppet_forge-5.0.4
13:25:50     Successfully installed log4r-1.1.10
13:25:50     Successfully installed cri-2.15.12
13:25:50     Successfully installed colored2-3.1.2
13:25:50     Successfully installed r10k-4.1.0
13:25:50     Parsing documentation for minitar-0.12.1
13:25:50     Installing ri documentation for minitar-0.12.1
```

Because of [this](https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppetserver_integration-system_no-conditional_smoke-7.x/) pipeline failure, the changes pushed to `7.x` are not being merged into the `main` branch.

2024-09-27 15:34 UTC, donoghuc requested changes
@span786 When we find breaking behaviors in tests on LTS streams it is important to figure out why they start failing instead of just papering over it. 

I have done some investigation here as an example of how you might track down the core of the issue so you can apply similar logic in the future. 

I was able to extract a stack trace (this is achieved by installing and agent build from `https://builds.delivery.puppetlabs.net/puppet-agent/e54dfdda31a4e1f69e1de58da110ab8f9d53055d` on a rhel9 vm then doing the gem install with `--debug --verbose --trace` options)
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `start_with' for "RDoc::Markup::Document":String
Did you mean?  start_with?
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:978:in `block in <class:Store>'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:971:in `load'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:971:in `block in marshal_load'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:971:in `open'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:971:in `marshal_load'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:616:in `load_class_data'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:596:in `load_class'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:806:in `save_class'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:748:in `block in save'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:747:in `each'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/store.rb:747:in `save'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/generator/ri.rb:27:in `generate'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:137:in `block in document'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:134:in `chdir'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:134:in `document'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:193:in `generate'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:55:in `each'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rdoc/rubygems_hook.rb:55:in `generation_hook'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/request_set.rb:323:in `block in install_hooks'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/request_set.rb:322:in `each'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/request_set.rb:322:in `install_hooks'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/request_set.rb:221:in `install'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/commands/install_command.rb:208:in `install_gem'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/commands/install_command.rb:224:in `block in install_gems'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `each'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `install_gems'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/commands/install_command.rb:165:in `execute'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/command.rb:325:in `invoke_with_build_args'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/command_manager.rb:178:in `process_args'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/command_manager.rb:148:in `run'
	/opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/gem_runner.rb:59:in `run'
	/opt/puppetlabs/puppet/bin/gem:21:in `<main>'
```
This points to exactly where the bug is (`start_with` instead of `start_with?`). What was immediately interesting to me was that you can see from the ruby source code https://github.com/ruby/ruby/blame/v2_7_8/lib/rdoc/store.rb that this file is very stable and does not contain the bug. With this information I knew that it must be an issue with how we are building ruby. With this information I went to look at patches we are applying when we build ruby in puppet runtime and found https://github.com/puppetlabs/puppet-runtime/commit/8954d1b3b4d349435eba0ae9cd0e3df64ce32000 

We can see that the bug was introduced in the `0001-Filter-marshaled-objects-ruby30.patch`. We can take this information and either contribute a bugfix to the upstream patch and/or update our build. 

We therefore do not want this change in puppetserver as it is correctly identifying  a bug in our packaging. We can close this and help get the bug fixed upstream.

2024-09-27 15:48 UTC, donoghuc commented
Looks like they fixed this in ruby 3 https://github.com/ruby/ruby/commit/385c31e770566b2f07f3222464f08886fcedc31e

2024-09-27 15:53 UTC, donoghuc commented
Filed https://perforce.atlassian.net/browse/PA-7089 to track this work internally.

2024-09-27 15:53 UTC, closed without merging

2024-09-30 06:32 UTC, span786 commented
Thank you so much, @donoghuc, for your valuable insights. 
Moving forward, I'll ensure to follow similar steps to identify the root cause of such issues.